version: '3.1'

services:
  mongo:
    image: mongo
    ports:
     - "27017:27017"
  mongo_express:
    image: mongo-express
    ports:
     - "8081:8081"
  web:
    build: .
    depends_on:
     - mongo
     - mongo_express
    ports:
     - "3000:3000"
    volumes:
     - .:/app
